version: "3.9"
services:
  jenkins:
    container_name: jenkins_dev
    image: jenkins/dotnet
    build:
      dockerfile: ./jenkins/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - F:/DockerVolumes/jenkins_home:/var/jenkins_home
    networks:
      - net
  rabbitmq:
    container_name: rabbitmq_dev
    image: rabbitmq:3.9-management
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - F:/DockerVolumes/rabbitmq_home:/var/rabbitmq_home
    networks:
      - net
  mssql: # Database
    container_name: mssql_dev
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Master@123
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - F:/DockerVolumes/mssql_home:/var/mssql_home
    networks:
      - net
  mysql: # Database
    container_name: mysql_dev
    image: mysql
    restart: always
    volumes:
      - F:/DockerVolumes/mysql_home:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: Master@123
    ports:
      - 3306:3306
    networks:
      - net
  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - 5341:80
    volumes:
      - F:/DockerVolumes/seq_home:/var/seq_home
    environment:
      - ACCEPT_EULA=Y
    networks:
      - net
  zookeeper:
    container_name: zookeeper_dev
    image: confluentinc/cp-zookeeper:latest
    volumes: 
      - F:/DockerVolumes/zookeeper_home/data:/var/lib/zookeeper/data
      - F:/DockerVolumes/zookeeper_home/log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks: 
      - net
  kafka:
    container_name: kafka_dev
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    volumes:
      - F:/DockerVolumes/kafka_home:/var/lib/kafka
    networks: 
      - net
  grafana:
    container_name: grafana_dev
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - F:/DockerVolumes/grafana_home:/var/lib/grafana
    networks:
      - net
  prometheus:
    container_name: prometheus_dev
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - F:/DockerVolumes/prometheus_home:/etc/prometheus/
      # You need to place prometheus.yml file in the folder.
      - F:/DockerVolumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - net
  graphite:
    container_name: graphite_dev
    image: hopsoft/graphite-statsd
    ports:
      - 81:81
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
    networks:
      - net
  glue_jupyter:
    container_name: glue_jupyter
    command: /home/glue_user/jupyter/jupyter_start.sh
    environment:
      - DISABLE_SSL=true
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    ports:
      - 4040:4040
      - 18080:18080
      - 8998:8998
      - 8888:8888
    restart: always
    volumes:
      - F:/DockerVolumes/glue_jupyter:/home/glue_user/.aws
      - F:/DockerVolumes/glue_jupyter_workspace/:/home/glue_user/workspace/jupyter_workspace/
  mongodb: # Database
    container_name: mongo_dev
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: Master123456
    ports:
      - 27017:27017
    volumes:
      - F:/DockerVolumes/mongo_data:/data/db
    networks:
      - net
  postgresql:
    container_name: postgresql_dev
    image: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - F:/DockerVolumes/postgresql_home:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Master@123
networks:
  net:
