version: "3.9"
services:
  jenkins:
    container_name: jenkins_dev
    image: jenkins/dotnet
    build:
      context: dockerindockerjenkins
    ports:
      - 8080:8080
    volumes:
      - "/home/jenkins_home:/var/jenkins_home"
    networks:
      - net
  rabbitmq:
    container_name: rabbitmq_dev
    image: rabbitmq:3.9-management
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - "/home/rabbitmq_home:/var/rabbitmq_home"
    networks:
      - net
  mssql:
    container_name: mssql_dev
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Master@123
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - "/mnt/development/docker-volumes/mssql_home:/var/mssql_home"
    networks:
      - net
  mysql:
    container_name: mysql_dev
    image: mysql
    restart: always
    volumes:
      - /mnt/development/docker-volumes/mysql_home:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: Master@123
    ports:
      - 3306:3306
    networks:
      - net
  postgresql:
    container_name: postgresql_dev
    image: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - /mnt/development/docker-volumes/postgresql_home:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Master@123
  h2-db:
    image: oscarfonts/h2
    container_name: h2-database
    ports:
      - 1521:1521
      - 81:81
    environment:
      - H2_OPTIONS=-ifNotExists
    volumes:
      - /mnt/development/docker-volumes/h2_db_home:/opt/h2-data
networks:
  net: